#!/bin/bash 

handle_shutdown() {
	echo Received SIGTERM in $0
	if [ ! -z "${PROC}" ]; then
		kill ${PROC}
	fi
	exit 0;
}

trap "handle_shutdown" SIGTERM

python ./py_de_id/py-de-id.py &
PROC=$!

while true; do
	sleep 1
done