#!/bin/bash 

handle_shutdown() {
	echo Received SIGTERM in $0
	if [ ! -z "${PROC}" ]; then
		kill ${PROC}
	fi
	exit 0;
}

trap "handle_shutdown" SIGTERM

flask run --host 0.0.0.0 --port 5000 &
PROC=$!

while true; do
	sleep 1
done